### ISSUE TITLE
I can't watch my .hbs files, without importing in index.js

### ISSUE THREAD

**Issue by rca-tiago-salomon** [raviroshan/assemble-webpack#5]
Thats my file:
```js
module.exports = {
  entry: config.src + config.app + 'index.js',
  output: {
    path: path.join(__dirname, 'dist'),
    publicPath: './',
    filename: 'js/[name].js'
  },
  module: {
    rules: [
      {
        test: /\.(hbs)$/,
        use: [
          {
            loader: 'assemble-webpack'
          }
        ]
      }
    ]
  },
  plugins: [
      new assembleWebpack.AttachedPlugin({
      baseLayout: config.src + 'layouts/default.hbs',
      basePages: [config.src + 'pages/**/*.hbs'],
      partialsLayout: [config.src + 'components/**/*.hbs'],
        partialsData: [
          config.src + 'components/**/*.json',
          config.src + 'pages/**/*.json'
        ],
      //helpers: config.src + 'helpers/handlebars-helpers.js',
      })
    ]
}
```

**Comment by raviroshan** [comment]
@rca-tiago-salomon : yes, that is intentional.
You may have 100 of HBS component and probably utilizing 70-80 of them in actual development [due to upgrade, code changes etc].

In general, every HBS component will have respective JS and SCSS files.
Prefer importing that component's JS file in index.js which should internally imports `HBS` and `SCSS` and keeps watching for any change.

So when you comment out that single JS import, respective dependencies will not be part of webpack build.

Also, I would not like to keep an watcher on ALL the HBS files under my project until imported.

Hope that clarifies your issues. 🤞🏼
